# Generated by Django 3.0.6 on 2020-05-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200529_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='images/default.jpeg', upload_to='users/%Y/%m/%d'),
        ),
    ]
